### ISSUE TITLE
A couple issues

### ISSUE THREAD

**Issue by jojojames** [nicklanasa/xcode-mode#11]
Hey, using your xcode-mode. A couple ideas.

1.
(defun xcode-find-binaries ()
    (mapcar #'string-trim
                    (split-string
                     (shell-command-to-string "find ~/Library/Developer/Xcode/DerivedData/ -name *.app"))))

I believe _.app should be wrapped in '_.app'. I think later Xcode versions for builds are in DerivedData/appnamerandom123123/build/etc/etc. Also we might want to be able to let the user decide what the build directory can be. Maybe a buffer local?

Without this change, I was not able to get a list of apps to run.
1. Maybe some kind of memory on the last used directory. As of right now, I have to rechoose the app path everytime I launch.
2. We could potentially integrate with projectile mode to find the root of the project. Anytime I'm in a file that's not at the root, all the commands fail (I'm guessing because it's using the current working directory).
3. When rerunning a build, I believe there's a couple key presses that needs to happen before the build starts. (e.g. asks if we want to kill running compile, press y or no). We could streamline this a bit.

I'd be happy to try to implement some of this as time allows.

**Comment by nicklanasa** [comment]
@jojojames Sorry for the delayed response. For some reason, I didn't get the notification. All these changes seem great! Go ahead and implement them whenever you can. 

I didn't know you could use projectile to get the project root, this is awesome because as you probably already know we have to be the `.xctool-args` file to run any of the `xcode-mode` commands. 

Also, I usually just hit `g` in the `compilation-buffer` to restart the build. It's usually to just rerun the same .app file (that is overwritten) when `xcode-xctool-build` is done. So, usually what I do is switch to `xctool-args`, rerun `xcode-xctool-build` - `C-c C-x bb` then `xcode-xctool-build-and-run` to rerun the app. 

Either way, your proposed changes will be a huge help and would love to add more features to `xcode-mode` as I use it on a regular basis for work and other projects. 

Let me know what you think.

**Comment by nicklanasa** [comment]
Also, I've been using `xcode-xctool-build-and-run` - `C-c C-x br` to build and prompt to select an app to run with `ios-sim`. I like this flow but I think it could be better.

**Comment by jojojames** [comment]
Thanks, those are some good tips on how to use xcode-mode. I'll try to incorporate them in my own workflow.

I'll try and get some improvements in as time frees up.
